spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rbacdb
    username: rbacuser
    password: rbacpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
